@extends('layout.main')

@section('content')
<div class="container">

    <h1>bambini</h1>

    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sequi, quidem officiis similique architecto optio neque eveniet aperiam assumenda in consequuntur, esse nulla iste dicta quibusdam amet reiciendis omnis, est nisi! Modi eos delectus maxime ullam! Nihil, neque itaque perspiciatis distinctio aut minus incidunt mollitia veritatis nobis quasi laudantium est excepturi repellendus fugiat. Quo quos expedita rerum porro laudantium dicta asperiores placeat doloribus quibusdam aspernatur minima dolorum a itaque nesciunt magni mollitia, nostrum inventore, ut quis error, nam quae necessitatibus voluptatibus? Necessitatibus, quaerat ipsum? Accusamus ea accusantium autem ut assumenda ex aliquam aperiam, perferendis sequi magni cumque minus eaque nesciunt debitis suscipit nobis. Pariatur deserunt fuga itaque eum deleniti et ipsum quidem atque fugiat, molestias ad. Fuga, cum! Aspernatur ratione earum numquam repellat, ex a maxime, in fugiat culpa porro eveniet accusamus? Soluta, labore numquam vel odio accusantium inventore saepe ea. Molestiae maxime voluptas unde. Sint autem commodi repudiandae quia! Eius saepe adipisci quas officiis mollitia vel? Iste exercitationem cupiditate at quasi officia dolores nam, distinctio blanditiis ipsum velit accusamus eos vel nemo odit labore libero similique. Magnam commodi earum eum quae, adipisci est debitis assumenda a cupiditate accusantium quasi eius numquam quo quia officia cum repudiandae, dolor aspernatur quidem sit mollitia quaerat libero. Ex, animi eius fugiat repellat, aspernatur expedita deleniti ipsa placeat dicta cumque maiores delectus voluptas quos voluptates corporis quod? Doloremque nulla reiciendis, mollitia, ratione tempora inventore accusantium voluptatum, eveniet harum maxime odit. Minima distinctio culpa illo beatae cum impedit accusamus tempora in deserunt vitae aspernatur reprehenderit expedita laudantium architecto, quas quia quod officia. Nam, deleniti doloribus autem maiores mollitia repellendus velit amet sint ea perspiciatis error omnis ut dolore repellat sit delectus magni animi maxime. Inventore rerum natus aspernatur deserunt iure et similique dicta, esse vel provident doloribus dolorum cumque voluptatum nobis delectus fugiat culpa reiciendis est!</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sequi, quidem officiis similique architecto optio neque eveniet aperiam assumenda in consequuntur, esse nulla iste dicta quibusdam amet reiciendis omnis, est nisi! Modi eos delectus maxime ullam! Nihil, neque itaque perspiciatis distinctio aut minus incidunt mollitia veritatis nobis quasi laudantium est excepturi repellendus fugiat. Quo quos expedita rerum porro laudantium dicta asperiores placeat doloribus quibusdam aspernatur minima dolorum a itaque nesciunt magni mollitia, nostrum inventore, ut quis error, nam quae necessitatibus voluptatibus? Necessitatibus, quaerat ipsum? Accusamus ea accusantium autem ut assumenda ex aliquam aperiam, perferendis sequi magni cumque minus eaque nesciunt debitis suscipit nobis. Pariatur deserunt fuga itaque eum deleniti et ipsum quidem atque fugiat, molestias ad. Fuga, cum! Aspernatur ratione earum numquam repellat, ex a maxime, in fugiat culpa porro eveniet accusamus? Soluta, labore numquam vel odio accusantium inventore saepe ea. Molestiae maxime voluptas unde. Sint autem commodi repudiandae quia! Eius saepe adipisci quas officiis mollitia vel? Iste exercitationem cupiditate at quasi officia dolores nam, distinctio blanditiis ipsum velit accusamus eos vel nemo odit labore libero similique. Magnam commodi earum eum quae, adipisci est debitis assumenda a cupiditate accusantium quasi eius numquam quo quia officia cum repudiandae, dolor aspernatur quidem sit mollitia quaerat libero. Ex, animi eius fugiat repellat, aspernatur expedita deleniti ipsa placeat dicta cumque maiores delectus voluptas quos voluptates corporis quod? Doloremque nulla reiciendis, mollitia, ratione tempora inventore accusantium voluptatum, eveniet harum maxime odit. Minima distinctio culpa illo beatae cum impedit accusamus tempora in deserunt vitae aspernatur reprehenderit expedita laudantium architecto, quas quia quod officia. Nam, deleniti doloribus autem maiores mollitia repellendus velit amet sint ea perspiciatis error omnis ut dolore repellat sit delectus magni animi maxime. Inventore rerum natus aspernatur deserunt iure et similique dicta, esse vel provident doloribus dolorum cumque voluptatum nobis delectus fugiat culpa reiciendis est!</p>

</div>
@endsection
