@extends('layout.main')

@section('content')
<div class="container">

    <h1>uomo</h1>

    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi accusantium earum repellendus, qui tempora, dolor, ut excepturi blanditiis ad praesentium veniam. Est veniam dignissimos iusto, ratione in nobis nisi vel minima voluptatum aliquid iste, recusandae animi ea, consectetur quo modi ab totam. Minima architecto perspiciatis, odio sint eligendi, animi hic, vero pariatur reprehenderit accusantium quia distinctio officia dicta delectus veniam quae! Ipsum officia, odio magni adipisci, incidunt unde praesentium ea, dolorem cum explicabo alias voluptates ipsa fuga asperiores facere neque delectus repudiandae nesciunt maiores provident nulla autem sed? Temporibus ipsam similique eveniet dignissimos provident unde facilis tempora voluptates excepturi nobis, architecto est cupiditate nam voluptatibus doloremque eius saepe consequatur eaque quaerat deleniti dolores reiciendis? Cupiditate quas, sunt nobis voluptate similique vitae inventore magni maiores eaque reiciendis error animi obcaecati sint? Eius perspiciatis unde ut eligendi magni non, culpa earum adipisci aliquid repellendus sapiente ex possimus dignissimos ipsum ipsam ad numquam. Corrupti accusamus, dolores omnis officia voluptas velit maiores, quo debitis porro neque a facilis, error provident ex laboriosam sed necessitatibus eveniet repudiandae aspernatur nostrum veritatis enim! Facilis beatae consequatur magnam alias dolores cum temporibus neque soluta natus quos! Officia provident hic ea est. Provident a nisi corrupti quos, sed soluta tempora doloremque repudiandae nesciunt illum ducimus eos officiis excepturi molestiae quidem dolorum beatae pariatur, doloribus ea sequi. Necessitatibus officiis dignissimos nam delectus non minima quidem architecto alias, optio est aliquid cum illo ipsam, impedit repellendus. Qui aliquam praesentium iure explicabo, veniam fuga cupiditate facilis commodi soluta esse libero, culpa perferendis nulla architecto a voluptate repellat tenetur. Sint blanditiis sunt eveniet ab ullam, unde rem dolorum esse qui voluptas natus labore deserunt placeat tenetur accusantium voluptatibus quidem excepturi eaque ea nulla. Vel facere sed enim maiores quisquam expedita est! Tempore autem perferendis harum numquam ducimus culpa assumenda accusamus asperiores praesentium quas.</p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi accusantium earum repellendus, qui tempora, dolor, ut excepturi blanditiis ad praesentium veniam. Est veniam dignissimos iusto, ratione in nobis nisi vel minima voluptatum aliquid iste, recusandae animi ea, consectetur quo modi ab totam. Minima architecto perspiciatis, odio sint eligendi, animi hic, vero pariatur reprehenderit accusantium quia distinctio officia dicta delectus veniam quae! Ipsum officia, odio magni adipisci, incidunt unde praesentium ea, dolorem cum explicabo alias voluptates ipsa fuga asperiores facere neque delectus repudiandae nesciunt maiores provident nulla autem sed? Temporibus ipsam similique eveniet dignissimos provident unde facilis tempora voluptates excepturi nobis, architecto est cupiditate nam voluptatibus doloremque eius saepe consequatur eaque quaerat deleniti dolores reiciendis? Cupiditate quas, sunt nobis voluptate similique vitae inventore magni maiores eaque reiciendis error animi obcaecati sint? Eius perspiciatis unde ut eligendi magni non, culpa earum adipisci aliquid repellendus sapiente ex possimus dignissimos ipsum ipsam ad numquam. Corrupti accusamus, dolores omnis officia voluptas velit maiores, quo debitis porro neque a facilis, error provident ex laboriosam sed necessitatibus eveniet repudiandae aspernatur nostrum veritatis enim! Facilis beatae consequatur magnam alias dolores cum temporibus neque soluta natus quos! Officia provident hic ea est. Provident a nisi corrupti quos, sed soluta tempora doloremque repudiandae nesciunt illum ducimus eos officiis excepturi molestiae quidem dolorum beatae pariatur, doloribus ea sequi. Necessitatibus officiis dignissimos nam delectus non minima quidem architecto alias, optio est aliquid cum illo ipsam, impedit repellendus. Qui aliquam praesentium iure explicabo, veniam fuga cupiditate facilis commodi soluta esse libero, culpa perferendis nulla architecto a voluptate repellat tenetur. Sint blanditiis sunt eveniet ab ullam, unde rem dolorum esse qui voluptas natus labore deserunt placeat tenetur accusantium voluptatibus quidem excepturi eaque ea nulla. Vel facere sed enim maiores quisquam expedita est! Tempore autem perferendis harum numquam ducimus culpa assumenda accusamus asperiores praesentium quas.</p>

</div>
@endsection
